//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PacketTracerEntities : DbContext
    {
        public PacketTracerEntities()
            : base("name=PacketTracerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstatusTransporte> EstatusTransportes { get; set; }
        public virtual DbSet<Paquete> Paquetes { get; set; }
        public virtual DbSet<Transporte> Transportes { get; set; }
        public virtual DbSet<Repartidor> Repartidors { get; set; }
    
        public virtual int PaqueteAdd(string instruccionEntrega, Nullable<decimal> peso, string direccionOrigen, string direccionEntrega, Nullable<System.DateTime> fechaEstimadaEntrega, string numeroGuia, byte[] codigoQR)
        {
            var instruccionEntregaParameter = instruccionEntrega != null ?
                new ObjectParameter("InstruccionEntrega", instruccionEntrega) :
                new ObjectParameter("InstruccionEntrega", typeof(string));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(decimal));
    
            var direccionOrigenParameter = direccionOrigen != null ?
                new ObjectParameter("DireccionOrigen", direccionOrigen) :
                new ObjectParameter("DireccionOrigen", typeof(string));
    
            var direccionEntregaParameter = direccionEntrega != null ?
                new ObjectParameter("DireccionEntrega", direccionEntrega) :
                new ObjectParameter("DireccionEntrega", typeof(string));
    
            var fechaEstimadaEntregaParameter = fechaEstimadaEntrega.HasValue ?
                new ObjectParameter("FechaEstimadaEntrega", fechaEstimadaEntrega) :
                new ObjectParameter("FechaEstimadaEntrega", typeof(System.DateTime));
    
            var numeroGuiaParameter = numeroGuia != null ?
                new ObjectParameter("NumeroGuia", numeroGuia) :
                new ObjectParameter("NumeroGuia", typeof(string));
    
            var codigoQRParameter = codigoQR != null ?
                new ObjectParameter("CodigoQR", codigoQR) :
                new ObjectParameter("CodigoQR", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaqueteAdd", instruccionEntregaParameter, pesoParameter, direccionOrigenParameter, direccionEntregaParameter, fechaEstimadaEntregaParameter, numeroGuiaParameter, codigoQRParameter);
        }
    
        public virtual int PaqueteDelete(Nullable<int> idPaquete)
        {
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("IdPaquete", idPaquete) :
                new ObjectParameter("IdPaquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaqueteDelete", idPaqueteParameter);
        }
    
        public virtual ObjectResult<PaqueteGetAll_Result> PaqueteGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaqueteGetAll_Result>("PaqueteGetAll");
        }
    
        public virtual ObjectResult<PaqueteGetById_Result> PaqueteGetById(Nullable<int> idPaquete)
        {
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("IdPaquete", idPaquete) :
                new ObjectParameter("IdPaquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaqueteGetById_Result>("PaqueteGetById", idPaqueteParameter);
        }
    
        public virtual int PaqueteUpdate(Nullable<int> idPaquete, string instruccionEntrega, Nullable<decimal> peso, string direccionOrigen, string direccionEntrega, Nullable<System.DateTime> fechaEstimadaEntrega, string numeroGuia, byte[] codigoQR)
        {
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("IdPaquete", idPaquete) :
                new ObjectParameter("IdPaquete", typeof(int));
    
            var instruccionEntregaParameter = instruccionEntrega != null ?
                new ObjectParameter("InstruccionEntrega", instruccionEntrega) :
                new ObjectParameter("InstruccionEntrega", typeof(string));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(decimal));
    
            var direccionOrigenParameter = direccionOrigen != null ?
                new ObjectParameter("DireccionOrigen", direccionOrigen) :
                new ObjectParameter("DireccionOrigen", typeof(string));
    
            var direccionEntregaParameter = direccionEntrega != null ?
                new ObjectParameter("DireccionEntrega", direccionEntrega) :
                new ObjectParameter("DireccionEntrega", typeof(string));
    
            var fechaEstimadaEntregaParameter = fechaEstimadaEntrega.HasValue ?
                new ObjectParameter("FechaEstimadaEntrega", fechaEstimadaEntrega) :
                new ObjectParameter("FechaEstimadaEntrega", typeof(System.DateTime));
    
            var numeroGuiaParameter = numeroGuia != null ?
                new ObjectParameter("NumeroGuia", numeroGuia) :
                new ObjectParameter("NumeroGuia", typeof(string));
    
            var codigoQRParameter = codigoQR != null ?
                new ObjectParameter("CodigoQR", codigoQR) :
                new ObjectParameter("CodigoQR", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaqueteUpdate", idPaqueteParameter, instruccionEntregaParameter, pesoParameter, direccionOrigenParameter, direccionEntregaParameter, fechaEstimadaEntregaParameter, numeroGuiaParameter, codigoQRParameter);
        }
    
        public virtual ObjectResult<RepartidorGetAll_Result> RepartidorGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepartidorGetAll_Result>("RepartidorGetAll");
        }
    
        public virtual ObjectResult<RepartidorGetById_Result> RepartidorGetById(Nullable<int> idRepartidor)
        {
            var idRepartidorParameter = idRepartidor.HasValue ?
                new ObjectParameter("IdRepartidor", idRepartidor) :
                new ObjectParameter("IdRepartidor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RepartidorGetById_Result>("RepartidorGetById", idRepartidorParameter);
        }
    }
}
